name: CI

on:
  push:

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oknozor/cocogitto-action@v3
        with:
          check-latest-tag-only: true
