name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oknozor/cocogitto-action@v3
        with:
          git-user: "Cog Bot"
          check-latest-tag-only: true
      - run: cog bump --auto
      - run: git push --tags
      - run: echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
        id: tag
      - run: cog changelog --at ${{ steps.tag.outputs.tag }} > CHANGELOG.md
      - uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            CHANGELOG.md
            README.md
            LICENSE
          discussion_category_name: Announcements
